// eggCarousel/client/src/views/Login/index.jsx
import React, { Component } from "react";
import { Form, Icon, Input, Button } from "antd";
import axios from "@/utils/httpAxios";
import "@/common/css/login.css"
class Login extends Component {
  state = {};
  handleSubmit = e => {
    e.preventDefault();
    this.props.form.validateFields((err, values) => {
      if (!err) {
        axios.post("/user/login",values).then(res=>{
            if(res.data.code === 1){
                window.sessionStorage.token = res.data.token;
                this.props.history.replace("/home")
            }
        })
      }
    });
  };
  render() {
    const { getFieldDecorator } = this.props.form;
    return (
      <Form onSubmit={this.handleSubmit} className="login-form">
        <Form.Item>
          {getFieldDecorator("username", {
            rules: [{ required: true, message: "Please input your username!" }]
          })(
            <Input
              prefix={<Icon type="user" style={{ color: "rgba(0,0,0,.25)" }} />}
              placeholder="Username"
            />
          )}
        </Form.Item>
        <Form.Item>
          {getFieldDecorator("password", {
            rules: [{ required: true, message: "Please input your Password!" }]
          })(
            <Input
              prefix={<Icon type="lock" style={{ color: "rgba(0,0,0,.25)" }} />}
              type="password"
              placeholder="Password"
            />
          )}
        </Form.Item>
        <Form.Item>
          <Button
            type="primary"
            htmlType="submit"
            className="login-form-button"
          >
            Log in
          </Button>
          Or <a href="/register">register now!</a>
        </Form.Item>
      </Form>
    );
  }
}

export default Form.create({ name: "normal_login" })(Login);

// 10.26modi/client/src/views/login.vue
<template>
  <div>
    <input type="text" placeholder="用户名" v-model="username" />
    <br />
    <input type="password" placeholder="密码" v-model="password" />
    <br />
    <button @click="login">login</button>
  </div>
</template>

<script>
import axios from "@/utils/http";
export default {
  data() {
    return {
      username: "",
      password: ""
    };
  },
  methods: {
    login() {
      const { username, password } = this;
      axios.post("/api/user/login", { username, password }).then(res => {
        if (res.data.code === 1) {
          window.sessionStorage.token = res.data.token;
        }
        this.$router.replace("/list");
      });
    }
  }
};
</script>

<style>
</style>
